 #definicion del proyecto en docker
  
    # servicios a ejecutar
    services:
        # MySQL con nombre `red-db`
        db:
            image: mysql:8.0.31
            container_name: red-db
            environment:
            - MYSQL_DATABASE=red
            - MYSQL_USER=red
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
            ports:
            - '3306:3306'
            expose:
            - '3306'